-- 기획서 7장 데이터 모델 + 9장 요금제 + 리프레시 토큰.
--
-- 좌표는 전부 geography(Point, 4326). 넣을 때는 ST_MakePoint(lng, lat) — 경도가 먼저다.
-- enum 성격의 컬럼은 PostgreSQL ENUM 타입 대신 varchar + CHECK로 둔다.
-- 값을 추가할 때 ALTER TYPE 없이 CHECK만 바꾸면 되고, Hibernate 스키마 검증과도 충돌하지 않는다.

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 카카오 로그인 사용자 식별자. 기획서 7장에는 없지만 카카오 로그인으로 가입하려면 필요하다.
    kakao_id    bigint       NOT NULL,
    name        varchar(50)  NOT NULL,
    avatar_url  varchar(500),
    created_at  timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT uq_users_kakao_id UNIQUE (kakao_id)
);

-- ---------------------------------------------------------------------------
-- clubs
-- ---------------------------------------------------------------------------
CREATE TABLE clubs (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             varchar(30)  NOT NULL,
    -- 디자인 시스템의 클럽 색 토큰 이름. 실제 색값은 프론트 테마가 가진다. 빨강 계열은 없다.
    color            varchar(10)  NOT NULL,
    -- 클럽장. 클럽장이 탈퇴해도 클럽과 멤버의 기록은 남아야 하므로 NULL로 풀어준다.
    created_by       bigint       REFERENCES users (id) ON DELETE SET NULL,
    invite_code      varchar(32)  NOT NULL,
    -- 무료 제한값(정원·스캔 기간·클럽 수)은 여기 두지 않고 애플리케이션 설정으로 관리한다.
    plan             varchar(10)  NOT NULL DEFAULT 'FREE',
    plan_expires_at  timestamptz,
    created_at       timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT uq_clubs_invite_code UNIQUE (invite_code),
    CONSTRAINT ck_clubs_color CHECK (color IN ('SAGE', 'SKY', 'SAND', 'LILAC')),
    CONSTRAINT ck_clubs_plan  CHECK (plan IN ('FREE', 'PAID'))
);

-- ---------------------------------------------------------------------------
-- club_members
-- ---------------------------------------------------------------------------
CREATE TABLE club_members (
    club_id    bigint       NOT NULL REFERENCES clubs (id) ON DELETE CASCADE,
    user_id    bigint       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    joined_at  timestamptz  NOT NULL DEFAULT now(),

    PRIMARY KEY (club_id, user_id)
);

-- 권한 검증("요청자가 이 클럽 멤버인가", "내 클럽 목록")이 거의 모든 조회에서 user_id로 들어온다.
-- PK는 (club_id, user_id) 순서라 user_id 단독 조회에는 쓰이지 않는다.
CREATE INDEX ix_club_members_user_id ON club_members (user_id);

-- ---------------------------------------------------------------------------
-- places
-- ---------------------------------------------------------------------------
CREATE TABLE places (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           varchar(100)            NOT NULL,
    address        varchar(255),
    coordinate     geography(Point, 4326)  NOT NULL,
    category       varchar(100),
    source         varchar(10)             NOT NULL,
    -- 카카오 장소 ID. source=API일 때만 있다.
    external_id    varchar(50),
    created_by     bigint                  REFERENCES users (id) ON DELETE SET NULL,
    -- source=USER 커스텀 장소의 소속 클럽. 이 클럽 안에서만 후보로 노출한다.
    club_id        bigint                  REFERENCES clubs (id) ON DELETE CASCADE,
    category_tags  text[]                  NOT NULL DEFAULT '{}',
    created_at     timestamptz             NOT NULL DEFAULT now(),

    CONSTRAINT ck_places_source CHECK (source IN ('API', 'USER')),
    -- 카카오 장소는 모두가 공유하고(클럽 없음), 커스텀 장소는 반드시 한 클럽에 속한다.
    CONSTRAINT ck_places_source_shape CHECK (
        (source = 'API'  AND external_id IS NOT NULL AND club_id IS NULL) OR
        (source = 'USER' AND external_id IS NULL     AND club_id IS NOT NULL)
    )
);

-- 같은 카카오 가게는 한 행으로 모인다. 조회 전 이 값으로 먼저 찾고, 있으면 카카오를 호출하지 않는다.
CREATE UNIQUE INDEX uq_places_external_id ON places (external_id) WHERE source = 'API';
CREATE INDEX ix_places_coordinate    ON places USING GIST (coordinate);
CREATE INDEX ix_places_club_id       ON places (club_id) WHERE club_id IS NOT NULL;
CREATE INDEX ix_places_category_tags ON places USING GIN (category_tags);

-- ---------------------------------------------------------------------------
-- visits
-- ---------------------------------------------------------------------------
CREATE TABLE visits (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 회원 탈퇴 시 내 기록도 함께 지운다 (기획서 C-04).
    user_id     bigint        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    place_id    bigint        NOT NULL REFERENCES places (id),
    -- 클럽이 없어도 기록할 수 있어야 한다 ("혼자서도 완결"). 그 경우 기록은 PRIVATE다.
    club_id     bigint        REFERENCES clubs (id),
    rating      varchar(5)    NOT NULL,
    memo        varchar(200),
    visited_at  timestamptz   NOT NULL,
    visibility  varchar(10)   NOT NULL DEFAULT 'CLUB',
    created_at  timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT ck_visits_rating     CHECK (rating IN ('AGAIN', 'OKAY', 'NOPE')),
    CONSTRAINT ck_visits_visibility CHECK (visibility IN ('CLUB', 'PRIVATE')),
    CONSTRAINT ck_visits_club_visibility CHECK (visibility = 'PRIVATE' OR club_id IS NOT NULL)
);

-- 지도·주변 검색: 클럽 경계 안에서 장소별로 모은다.
CREATE INDEX ix_visits_club_place ON visits (club_id, place_id) WHERE club_id IS NOT NULL;
-- 내 기록 목록 (최근순)
CREATE INDEX ix_visits_user_visited_at ON visits (user_id, visited_at DESC);
-- 장소 상세: 한 장소의 방문 기록
CREATE INDEX ix_visits_place_id ON visits (place_id);

-- ---------------------------------------------------------------------------
-- visit_photos
-- ---------------------------------------------------------------------------
CREATE TABLE visit_photos (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id         bigint                  NOT NULL REFERENCES visits (id) ON DELETE CASCADE,
    -- 원본은 서버에 올리지 않는다. 썸네일 주소만 둔다.
    thumb_url        varchar(500)            NOT NULL,
    taken_at         timestamptz,
    exif_coordinate  geography(Point, 4326),
    -- 검색 인덱스 용도. 확신도가 낮으면 비워 둔다.
    tags             text[]                  NOT NULL DEFAULT '{}',
    tag_source       varchar(10),
    created_at       timestamptz             NOT NULL DEFAULT now(),

    CONSTRAINT ck_visit_photos_tag_source CHECK (tag_source IN ('ON_DEVICE', 'SERVER')),
    -- 태그가 없으면 출처도 없다.
    CONSTRAINT ck_visit_photos_tags_source CHECK (cardinality(tags) = 0 OR tag_source IS NOT NULL)
);

CREATE INDEX ix_visit_photos_visit_id        ON visit_photos (visit_id);
CREATE INDEX ix_visit_photos_tags            ON visit_photos USING GIN (tags);
CREATE INDEX ix_visit_photos_exif_coordinate ON visit_photos USING GIST (exif_coordinate);

-- ---------------------------------------------------------------------------
-- refresh_tokens (회전 방식)
-- ---------------------------------------------------------------------------
-- 갱신할 때마다 새 토큰을 발급하고 이전 토큰은 revoked_at을 채운다. 같은 로그인에서 이어진 토큰은
-- family_id를 공유한다. 이미 폐기된 토큰이 다시 들어오면 탈취로 보고 그 family 전체를 폐기한다.
CREATE TABLE refresh_tokens (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    -- 토큰 원문은 저장하지 않는다. DB가 유출돼도 바로 쓸 수 없게 SHA-256 해시(hex)만 둔다.
    token_hash  varchar(64)  NOT NULL,
    family_id   uuid         NOT NULL,
    expires_at  timestamptz  NOT NULL,
    revoked_at  timestamptz,
    created_at  timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT uq_refresh_tokens_token_hash UNIQUE (token_hash)
);

CREATE INDEX ix_refresh_tokens_family_id ON refresh_tokens (family_id);
CREATE INDEX ix_refresh_tokens_user_id   ON refresh_tokens (user_id);
